function write_input_file(newInputFile, nodesFile, bcfile, temp_final, mat_param)
%
% This function simply reads the template.inp file and replaces the
% names of the necessary files by the random string-based file names
% generated by the MATLAB codes.
%

originalFile = 'template.inp';

% Read txt into cell A
fid = fopen(originalFile,'r');
i = 1;
tline = fgetl(fid);
A{i} = tline;
while ischar(tline)
    i = i+1;
    tline = fgetl(fid);
    
    % Add the Nodes file
    k = strfind(tline, 'Add Nodes File');
    if (numel(k) > 0)
        tline = strrep(tline, 'Add Nodes File', nodesFile);
    end

    % Add Material Parameters
    k = strfind(tline, '*Add Material Substrate Properties');
    if (numel(k) > 0)
        tline = strrep(tline, '*Add Material Substrate Properties',['*Material, name=Material-Substrate',...
            newline,'*Density',newline,...
            num2str(0.0001),newline,...
            '*ELASTIC', newline,...
            num2str(mat_param(1)), ',', num2str(mat_param(2)), newline,...
             '*EXPANSION, TYPE = ORTHOTROPIC', newline,...
            num2str(mat_param(3)),',', num2str(mat_param(3)),',', num2str(-mat_param(3))]);
    end
    
%     k = strfind(tline, '*Add Material Kirigami Properties');
%     if (numel(k) > 0)
%         tline = strrep(tline, '*Add Material Kirigami Properties',['*ELASTIC', newline,...
%             num2str(mat_param(1)), ',', num2str(mat_param(2)), newline,...
%              '*EXPANSION, TYPE = ORTHOTROPIC', newline,...
%             num2str(mat_param(3)),',', num2str(mat_param(3)),',', num2str(-mat_param(3))]);
%     end
    
    k = strfind(tline, '*Add Material Kirigami Properties');
    if (numel(k) > 0)
        newmaterial = '';
        nLayers = length(mat_param)-5;
        for j=1:nLayers
            newmaterial = [newmaterial,'*Material, name=Material-Kirigami',num2str(j),newline,...
                '*Density',newline,num2str(0.001),newline];
            newmaterial = [newmaterial, '*ELASTIC', newline,...
               num2str(mat_param(4)), ',', num2str(mat_param(5)), newline,...
                '*EXPANSION, TYPE = ORTHOTROPIC', newline,...
                num2str(mat_param(5+j)),',', num2str(mat_param(5+j)),',', num2str(mat_param(5+j))];
            if j~=nLayers
                newmaterial = [newmaterial,newline];
            end
        end
        
        tline = strrep(tline, '*Add Material Kirigami Properties',newmaterial);
    end
    
    % Add the Boundary Condition file
    k = strfind(tline, 'Add Boundary Conditions File');
    if (numel(k) > 0)
        tline = strrep(tline, 'Add Boundary Conditions File', bcfile);
    end
    
    % Add the Boundary Condition file
    k = strfind(tline, 'Add Temperature');
    if (numel(k) > 0)
        tline = strrep(tline, 'Add Temperature', ['NodeAll,',num2str(temp_final)]);
    end
    
    A{i} = tline;
end
fclose(fid);

% Write cell A into txt
fid = fopen(newInputFile, 'w');
for i = 1:numel(A)
    if A{i+1} == -1
        fprintf(fid,'%s', A{i});
        break
    else
        fprintf(fid,'%s\n', A{i});
    end
end
end
